### ISSUE TITLE
Photoset Grid Crop the images from bottom

### ISSUE THREAD

**Issue by Gergely** [osCommerce/oscommerce2#575]
Code Reason: https://github.com/stylehatch/photoset-grid/blob/master/jquery.photoset-grid.js#L264

If images are in grid layout all bottom of the images croped.
Its criminal when png/gif images with alpha chanel used.

Test it on official page: http://stylehatch.github.io/photoset-grid/

(Click on **Adding A Lightbox** examples and compare the grid and pop-up image bottom differencies)

All advice is apprechiated
(Large invisible alpha chanel border on origin images is not acceptable)

**Comment by osc2nuke** [comment]
i can see it on the official page, but i think that is not how it is implemented/called into OSC.
The live site example shows how to use their system as a grid.
I am not sure if that affect osc.
And if that is a side effect of an in use script and disturb someone, future market is open to anyone to make an App for improve the images gallery/handling.
But i must give credit in noticing, i think no one ever seen or complained of it.

**Comment by Gergely** [comment]
user.css
```css
/* user.css ----------------------------------------------------------------- */
/* photoset main image bottom crop fix */
div.photoset-row.cols-1 {height: 250px !important;}
```
